# Site settings
title: Your awesome title
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://yourdomain.com"

menu:
  - title: "Продукция"
    url: '/katalog'
  - title: "Гарантия и доставка"
    url: '/garant/'
  - title: "Спецпредложения"
    url: '/spec/'
  - title: "Подогреватели"
    url: '/teploobmen/'
  - title: "Статьи"
    url: '/poleznaya/'
  - title: "Новости"
    url: '/news/'
#  - title: "Прайc"
#    url: '/price.html'

# Build settings
markdown: kramdown
permalink: pretty
