# Site settings
title: ООО Теплокомплект
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://yourdomain.com"

menu:
  - title: "Продукция"
    url: '/katalog.html'
  - title: "Гарантия и доставка"
    url: '/garant.html'
  - title: "Спецпредложения"
    url: '/spec.html'
  - title: "Подогреватели"
    url: '/teploobmen.html'
  - title: "Статьи"
    url: '/poleznaya.html'
  - title: "Новости"
    url: '/news.html'
#  - title: "Прайc"
#    url: '/price.html'

# Build settings
markdown: kramdown
permalink: pretty
